CREATE TABLE authors(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    birth_date date NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT authors_birth_date_not_in_future CHECK (birth_date <= CURRENT_DATE)
);

CREATE TABLE books(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    price numeric(12, 2) NOT NULL,
    publication_status varchar(20) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT books_price_non_negative CHECK (price >= 0),
    CONSTRAINT books_publication_status_valid CHECK (publication_status IN ('UNPUBLISHED', 'PUBLISHED'))
);

CREATE TABLE book_authors(
    book_id bigint NOT NULL,
    author_id bigint NOT NULL,
    PRIMARY KEY (book_id, author_id),
    CONSTRAINT fk_book_authors_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    CONSTRAINT fk_book_authors_author FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
);

CREATE INDEX idx_book_authors_author_id ON book_authors(author_id);

CREATE INDEX idx_books_publication_status ON books(publication_status);

CREATE OR REPLACE FUNCTION touch_updated_at()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN new;
END;
$$;

CREATE OR REPLACE FUNCTION forbid_book_unpublish()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF OLD.publication_status = 'PUBLISHED' AND NEW.publication_status = 'UNPUBLISHED' THEN
        RAISE EXCEPTION 'published books cannot be changed back to unpublished';
    END IF;
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN new;
END;
$$;

CREATE OR REPLACE FUNCTION ensure_book_has_author(target_book_id bigint)
    RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF EXISTS(
        SELECT
            1
        FROM
            books
        WHERE
            id = target_book_id)
        AND NOT EXISTS(
            SELECT
                1
            FROM
                book_authors
            WHERE
                book_id = target_book_id) THEN
        RAISE EXCEPTION 'book % must have at least one author', target_book_id;
END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_book_author_links_from_books()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM
        ensure_book_has_author(NEW.id);
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION validate_book_author_links_from_book_authors()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF tg_op IN('UPDATE', 'DELETE') THEN
        PERFORM
            ensure_book_has_author(OLD.book_id);
    END IF;
    IF tg_op IN('INSERT', 'UPDATE') THEN
        PERFORM
            ensure_book_has_author(NEW.book_id);
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_authors_touch_updated_at
    BEFORE UPDATE ON authors
    FOR EACH ROW
    EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_books_forbid_unpublish
    BEFORE UPDATE ON books
    FOR EACH ROW
    EXECUTE FUNCTION forbid_book_unpublish();

CREATE CONSTRAINT TRIGGER trg_books_require_author
    AFTER INSERT OR UPDATE ON books DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION validate_book_author_links_from_books();

CREATE CONSTRAINT TRIGGER trg_book_authors_require_author
    AFTER INSERT OR UPDATE OR DELETE ON book_authors DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION validate_book_author_links_from_book_authors();

